/* ==========================================================================
   Frigo — the master ingredient list
   --------------------------------------------------------------------------
   This is the list of tick-boxes Jerome starts from on the Fridge screen.
   Data only. No logic. Safe to edit by hand.

   Each line is:   ['name', 'aisle']            a normal item
              or:  ['name', 'aisle', true]      a staple — assumed always present,
                                                never counted as a missing ingredient

   'aisle' must be one of, and it decides where the item lands in the
   shopping list:
       produce · bakery · meat · dairy · dry · canned · frozen · spices · other

   Prefer editing this in items.html (open it in a browser) — it checks the
   aisle names for you and writes this file back out.
   ========================================================================== */
window.FRIGO_INGREDIENTS = {

  fridge: [
    ['eggs',            'dairy'],
    ['milk',            'dairy'],
    ['butter',          'dairy', true],
    ['heavy cream',     'dairy'],
    ['crème fraîche',   'dairy'],
    ['sour cream',      'dairy'],
    ['plain yogurt',    'dairy'],
    ['parmesan',        'dairy'],
    ['gruyère',         'dairy'],
    ['cheddar',         'dairy'],
    ['feta',            'dairy'],
    ['mozzarella',      'dairy'],
    ['dijon mustard',   'canned'],
    ['mayonnaise',      'canned'],
    ['ketchup',         'canned'],
    ['soy sauce',       'canned'],
    ['harissa',         'canned'],
    ['hot sauce',       'canned'],
    ['olives',          'canned'],
    ['pickles',         'canned'],
    ['lemons',          'produce'],
    ['limes',           'produce'],
    ['garlic',          'produce'],
    ['shallots',        'produce'],
    ['carrots',         'produce'],
    ['celery',          'produce'],
    ['bell peppers',    'produce'],
    ['mushrooms',       'produce'],
    ['spinach',         'produce'],
    ['tomatoes',        'produce'],
    ['cucumber',        'produce'],
    ['scallions',       'produce'],
    ['fresh parsley',   'produce'],
    ['fresh cilantro',  'produce'],
    ['fresh thyme',     'produce'],
    ['ginger',          'produce'],
    ['chicken thighs',  'meat'],
    ['chicken breast',  'meat'],
    ['ground beef',     'meat'],
    ['bacon',           'meat'],
    ['sausage',         'meat'],
    ['salmon',          'meat'],
    ['shrimp',          'meat'],
    ['tofu',            'other']
  ],

  freezer: [
    ['frozen peas',             'frozen'],
    ['frozen corn',             'frozen'],
    ['frozen spinach',          'frozen'],
    ['frozen green beans',      'frozen'],
    ['frozen broccoli',         'frozen'],
    ['frozen mixed vegetables', 'frozen'],
    ['frozen berries',          'frozen'],
    ['frozen chicken breast',   'frozen'],
    ['frozen chicken thighs',   'frozen'],
    ['frozen ground beef',      'frozen'],
    ['frozen shrimp',           'frozen'],
    ['frozen fish fillets',     'frozen'],
    ['frozen fries',            'frozen'],
    ['frozen dumplings',        'frozen'],
    ['puff pastry',             'frozen'],
    ['pie crust',               'frozen'],
    ['bread (frozen)',          'frozen'],
    ['ice cubes',               'frozen']
  ],

  pantry: [
    ['spaghetti',           'dry'],
    ['penne',               'dry'],
    ['orzo',                'dry'],
    ['egg noodles',         'dry'],
    ['white rice',          'dry'],
    ['basmati rice',        'dry'],
    ['arborio rice',        'dry'],
    ['couscous',            'dry'],
    ['bulgur',              'dry'],
    ['quinoa',              'dry'],
    ['lentils',             'dry'],
    ['chickpeas (dried)',   'dry'],
    ['all-purpose flour',   'dry', true],
    ['sugar',               'dry', true],
    ['brown sugar',         'dry'],
    ['baking powder',       'dry'],
    ['cornstarch',          'dry'],
    ['breadcrumbs',         'dry'],
    ['panko',               'dry'],
    ['rolled oats',         'dry'],
    ['honey',               'canned'],
    ['olive oil',           'canned', true],
    ['vegetable oil',       'canned', true],
    ['sesame oil',          'canned'],
    ['red wine vinegar',    'canned'],
    ['white wine vinegar',  'canned'],
    ['balsamic vinegar',    'canned'],
    ['tahini',              'canned'],
    ['peanut butter',       'canned'],
    ['canned tomatoes',     'canned'],
    ['tomato paste',        'canned'],
    ['canned chickpeas',    'canned'],
    ['canned white beans',  'canned'],
    ['canned coconut milk', 'canned'],
    ['canned tuna',         'canned'],
    ['chicken stock',       'canned'],
    ['vegetable stock',     'canned'],
    ['onions',              'produce'],
    ['potatoes',            'produce'],
    ['sweet potatoes',      'produce'],
    ['bread',               'bakery'],
    ['tortillas',           'bakery'],
    ['pita bread',          'bakery'],
    ['white wine',          'other'],
    ['red wine',            'other'],
    ['salt',                'spices', true],
    ['black pepper',        'spices', true]
  ],

  spices: [
    ['smoked paprika',      'spices'],
    ['sweet paprika',       'spices'],
    ['cumin',               'spices'],
    ['coriander',           'spices'],
    ['turmeric',            'spices'],
    ['cinnamon',            'spices'],
    ['cayenne pepper',      'spices'],
    ['chilli flakes',       'spices'],
    ['aleppo pepper',       'spices'],
    ['pul biber',           'spices'],
    ['sumac',               'spices'],
    ["za'atar",             'spices'],
    ['ras el hanout',       'spices'],
    ['baharat',             'spices'],
    ['garam masala',        'spices'],
    ['curry powder',        'spices'],
    ['dried oregano',       'spices'],
    ['dried thyme',         'spices'],
    ['dried rosemary',      'spices'],
    ['herbes de provence',  'spices'],
    ['bay leaves',          'spices'],
    ['dried mint',          'spices'],
    ['fennel seeds',        'spices'],
    ['mustard seeds',       'spices'],
    ['nutmeg',              'spices'],
    ['cardamom',            'spices'],
    ['cloves',              'spices'],
    ['star anise',          'spices'],
    ['garlic powder',       'spices'],
    ['onion powder',        'spices'],
    ['chilli powder',       'spices'],
    ['white pepper',        'spices'],
    ['saffron',             'spices'],
    ['vanilla extract',     'spices'],
    ['sesame seeds',        'spices']
  ]

};
